spring.application.name=Academi_Gymraeg
spring.datasource.url=jdbc:mysql://mysql.cs.bangor.ac.uk/dmd23ctz?serverTimezone= Europe/London
spring.datasource.username=dmd23ctz
spring.datasource.password=70ad6c2e03
spring.jpa.hibernate.ddl-auto=update